# Dockerfile.jenkins-agent
FROM gradle:7.6.1-jdk11

USER root

# Install Python, pip, pipenv
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl && \
    pip3 install pipenv && \
    ln -s /usr/local/bin/pipenv /usr/bin/pipenv

USER gradle