# Dockerfile.jenkins-agent
FROM gradle:7.6.1-jdk11

USER root
# Create the shared directory with proper permissions
RUN mkdir -p /shared-war && \
    chmod -R 777 /shared-war

# Optional: Set environment variables
ENV DEPLOY_DIR=/shared-war

# Install Python, pip, pipenv
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl docker.io && \
    pip3 install pipenv && \
    ln -s /usr/local/bin/pipenv /usr/bin/pipenv

USER gradle